version: '3.9'
networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

x-common-keys-core: &common-keys-core
  networks:
    - t2_proxy
  security_opt:
    - no-new-privileges:true
  restart: always

services:
  node-api:
    <<: *common-keys-core
    container_name: node-api-fullstack
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/node/app/app
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - '6030'
      - '6040'
    ports:
      - '6030:6030'
      - '6040:6040'
    command: node dist/app.js
    env_file:
      - .env

  mongo:
    <<: *common-keys-core
    container_name: mongo-container
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    expose:
      - '27017'
    ports:
      - '27017:27017'