export const grantList = [
  { "role": "GOD_ROLE", "resource": "admin", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "user", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "gamecard", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "tournament", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "team", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "team-roster", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "standing", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "slide", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "region", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "policy", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "organization", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "league", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "season", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "participant-team", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "participant-player", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "match", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "room", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "map", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "history", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "group", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "game", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "country", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "club", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "badge", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "bracket", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "blog", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "wildrift-stat", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "wildrift-pick", "action": "*", "attributes": ["*"] },
  { "role": "GOD_ROLE", "resource": "wildrift-ban", "action": "*", "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "user", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "gamecard", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "tournament", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "team", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "team-roster", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "standing", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "slide", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "region", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "policy", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "organization", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "league", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "season", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "participant-team", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "participant-player", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "match", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "room", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "map", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "history", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "group", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "game", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "country", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "club", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "bracket", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ADMIN_ROLE", "resource": "badge", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "user", "action": ["read"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "gamecard", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "tournament", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "team", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "team-roster", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "standing", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "organization", "action": ["read"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "league", "action": ["read"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "season", "action": ["read"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "participant-team", "action": ["read"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "participant-player", "action": ["read"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "match", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "room", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "map", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "history", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "group", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "club", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "bracket", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "EDITOR_ROLE", "resource": "badge", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "user", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "gamecard", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "tournament", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "team", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "team-roster", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "standing", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "organization", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "league", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "season", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "participant-team", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "participant-player", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "match", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "room", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "map", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "history", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "group", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "club", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "bracket", "action": ["read"], "attributes": ["*"] },
  { "role": "MODERATOR_ROLE", "resource": "badge", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "user", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "gamecard", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "tournament", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "team", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "team-roster", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "standing", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "organization", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "league", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "season", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "participant-team", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "participant-player", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "match", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "room", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "map", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "history", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "group", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "game", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "country", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "club", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "bracket", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_ROLE", "resource": "badge", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "user", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "gamecard", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "tournament", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "team", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "team-roster", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "standing", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "organization", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "league", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "season", "action": ["*"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "participant-team", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "participant-player", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "match", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "room", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "map", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "history", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "group", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "club", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "bracket", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_EDITOR_ROLE", "resource": "badge", "action": ["*", "!delete"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "user", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "gamecard", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "tournament", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "team", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "team-roster", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "standing", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "organization", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "league", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "season", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "participant-team", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "participant-player", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "match", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "room", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "map", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "history", "action": ["read", "update"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "group", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "club", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "bracket", "action": ["read"], "attributes": ["*"] },
  { "role": "ORGANIZER_MODERATOR_ROLE", "resource": "badge", "action": ["read"], "attributes": ["*"] }
]